# Generated by Django 5.1 on 2025-01-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='product',
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
