# Generated by Django 5.1 on 2025-01-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_productmodel_promotion_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='promotion_product',
            new_name='Promotion_product',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='slider_product',
            new_name='Slider_product',
        ),
    ]
