# Generated by Django 5.1 on 2025-01-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_rename_promotion_product_productmodel_promotion_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='Slider_background_img',
            field=models.BooleanField(default=False, help_text='Slider Background Image'),
        ),
    ]
