# Generated by Django 5.1 on 2025-01-15 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_productmodel_slider_background_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Slider_background_img',
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_img', models.ImageField(upload_to='assets/img/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productmodel')),
            ],
        ),
    ]
