# Generated by Django 5.1 on 2025-01-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0015_remove_productmodel_slider_background_img_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Slider_product',
        ),
    ]
